### ISSUE TITLE
move the files from the university server to dropbox

### ISSUE THREAD

**Issue by mesnilgr** [mesnilgr/is13#12]
no acces to data on http://www-etud.iro.umontreal.ca/~mesnilgr/ anymore

no possible download of http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold3.pkl.gz
and the perl evaluation script

cc @lucas0

**Comment by lucas0** [comment]
Thanks, @mesnilgr. So, how can I get the data?

**Comment by mesnilgr** [comment]
I'm now dealing with the university to get it. I don't have it.

**Comment by hadyelsahar** [comment]
@lucas0 , a quick fix for it is to download the [ATIS dataset](https://www.dropbox.com/s/3lxl9jsbw0j7h8a/atis.pkl?dl=0) yourself by updating the data/load.py file methods as follows : 
- update `load` function to download the ATIS dataset from this url instead  
- update `atisfull` to load the pickle file instead of the zip file
- update `atisfold` method to load the pickle file instead of the zip file and return validation dataset as well instead of train, test datasets only as encoded in atis.pkl file

**Comment by mesnilgr** [comment]
@hadyelsahar thanks a lot! I even forgot myself that I already had it moved here. :+1:

**Comment by lucas0** [comment]
Ok, changed the download URL, and deleted the '.gz' from the atis.pkl files, but I'm still getting

```
File "/Users/lucaslourenco/Developer/is13-master/data/load.py", line 33, in atisfold
train_set, valid_set, test_set, dicts = cPickle.load(f)
IOError: Not a gzipped file
```

what method should I use instead of cPickle.load(f)?

```
def load(filename):
    if not isfile(filename):
    download('https://www.dropbox.com/s/3lxl9jsbw0j7h8a/'+filename)
f = gzip.open(filename,'rb')
return f

def atisfull():
f = load(PREFIX + 'atis.pkl')
train_set, test_set, dicts = cPickle.load(f)
return train_set, test_set, dicts

def atisfold(fold):
assert fold in range(5)
f = load(PREFIX + 'atis.fold'+str(fold)+'.pkl')
train_set, valid_set, test_set, dicts = cPickle.load(f)
return train_set, valid_set, test_set, dicts
```

thats how load.py is right now. If there are any other changes I should perform, please let me know. Thank you for the alternative @hadyelsahar! 

P.S.: I know the issue is closed but since I couldn't apply the modifications suggested, could you help me with them @mesnilgr?

**Comment by tangkk** [comment]
should use f = open(filename,'rb') instead of gzip.open

**Comment by tangkk** [comment]
but since there is no conlleval.pl yet, I still can not run it

**Comment by tangkk** [comment]
and the conllevel.pl file can be found such as here:
https://www.comp.nus.edu.sg/~kanmy/courses/practicalNLP_2008/packages/conlleval.pl

**Comment by mesnilgr** [comment]
@tangkk every should work fine now. thanks for pointing this issue.
